[build]
builder = "NIXPACKS"

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"

[deploy]
postDeploy = "php artisan migrate --force"

[env]
APP_KEY = "base64:x/99Vv0/XpSG12OzNf/lkAhfox8beLpWRKj5fsN6qFA="
APP_URL = "https://tatakata.up.railway.app"
APP_DEBUG = "false"
APP_ENV = "production"
